#!/bin/bash

echo "🔍 DEBUGGING Azure Blood Stock 401 Errors"
echo "========================================="
echo ""

echo "Since LOCAL works but AZURE doesn't, the issue is likely:"
echo "1. Missing blood_stock table in Azure PostgreSQL"
echo "2. Environment variables not set in Azure App Service"
echo ""

echo "🧪 STEP 1: Check if blood_stock table exists in Azure PostgreSQL"
echo "=============================================================="
echo ""
echo "Connect to Azure PostgreSQL:"
echo "PGPASSWORD='AmmoEka1234' psql -h life-stream-postgres.postgres.database.azure.com -U lifestream_admin -d postgres"
echo ""
echo "Then run:"
echo "\\dt blood_stock"
echo ""
echo "If the table doesn't exist, you'll see: 'Did not find any relation named \"blood_stock\"'"
echo ""

echo "🧪 STEP 2: Test other hospital endpoints to confirm auth works"
echo "==========================================================="
echo ""
echo "Test these Azure endpoints (should work):"
echo "curl -X GET 'https://life-stream-backend-e8gmhvdgcmcaaxav.centralindia-01.azurewebsites.net/api/hospital/inventory' \\"
echo "  -H 'Cookie: connect.sid=YOUR_SESSION_COOKIE'"
echo ""
echo "curl -X GET 'https://life-stream-backend-e8gmhvdgcmcaaxav.centralindia-01.azurewebsites.net/api/hospital/dashboard/stats' \\"
echo "  -H 'Cookie: connect.sid=YOUR_SESSION_COOKIE'"
echo ""

echo "🧪 STEP 3: Test blood stock endpoints (should fail with 401)"
echo "========================================================="
echo ""
echo "curl -X GET 'https://life-stream-backend-e8gmhvdgcmcaaxav.centralindia-01.azurewebsites.net/api/hospital/blood-stock' \\"
echo "  -H 'Cookie: connect.sid=YOUR_SESSION_COOKIE'"
echo ""

echo "📋 MOST LIKELY SOLUTION:"
echo "========================"
echo ""
echo "The blood_stock table probably doesn't exist in Azure PostgreSQL."
echo "This causes database queries to fail, which the backend interprets as auth failure."
echo ""
echo "To fix:"
echo "1. Connect to Azure PostgreSQL"
echo "2. Create the blood_stock table using the SQL from azure-blood-stock-setup.sql"
echo "3. The 401 errors should disappear immediately"
echo ""

echo "💡 WHY THIS HAPPENS:"
echo "==================="
echo "- Local: blood_stock table exists ✅"
echo "- Azure: blood_stock table missing ❌"
echo "- Backend: Database query fails → returns 401 error"
echo "- Frontend: Sees 401 → shows 'login required'"
echo ""
echo "Authentication is working fine - it's a missing database table!"