#!/bin/bash

echo "🔧 Azure PostgreSQL Firewall Fix Guide"
echo "====================================="
echo ""

echo "🚨 ISSUE IDENTIFIED: Azure Firewall is blocking your connection"
echo ""
echo "📊 Connection Details:"
echo "- Azure Server: life-stream-postgres.postgres.database.azure.com"
echo "- Server IP: 4.213.16.95 (DNS resolution working ✅)"
echo "- Your Public IP: 2402:d000:810c:2729:59f1:2553:a439:ca05"
echo "- Port 5432: BLOCKED by firewall ❌"
echo ""

echo "🔧 SOLUTION: Add your IP to Azure PostgreSQL firewall rules"
echo ""
echo "📋 Step-by-Step Fix:"
echo ""
echo "1. **Open Azure Portal**:"
echo "   https://portal.azure.com"
echo ""
echo "2. **Navigate to your PostgreSQL server**:"
echo "   - Search for 'life-stream-postgres'"
echo "   - Click on your PostgreSQL server"
echo ""
echo "3. **Go to Connection Security**:"
echo "   - In the left menu, click 'Connection security'"
echo ""
echo "4. **Add Firewall Rule**:"
echo "   - Click '+ Add current client IP address'"
echo "   - OR manually add:"
echo "     * Rule name: MyLocalMachine"
echo "     * Start IP: 2402:d000:810c:2729:59f1:2553:a439:ca05"
echo "     * End IP: 2402:d000:810c:2729:59f1:2553:a439:ca05"
echo ""
echo "5. **Enable Azure Services** (recommended):"
echo "   - Set 'Allow access to Azure services' to 'Yes'"
echo ""
echo "6. **Save the changes**:"
echo "   - Click 'Save' at the top"
echo "   - Wait for the update to complete (may take 1-2 minutes)"
echo ""

echo "🧪 After making these changes, test the connection:"
echo ""
echo "# Simple connection test (run this after fixing firewall):"
echo "psql -h life-stream-postgres.postgres.database.azure.com -p 5432 -U lifestream_admin postgres"
echo ""

echo "⚠️  ALTERNATIVE: Use Azure Cloud Shell"
echo ""
echo "If you can't modify firewall rules, you can run the migration from Azure Cloud Shell:"
echo ""
echo "1. Go to https://shell.azure.com"
echo "2. Choose Bash"
echo "3. Run the migration commands from there"
echo ""

echo "📞 Need help with Azure Portal?"
echo ""
echo "If you need help finding these settings:"
echo "1. Azure Portal → All Resources → 'life-stream-postgres'"
echo "2. Left sidebar → Settings → Connection security"
echo "3. Look for 'Firewall rules' section"
echo ""

read -p "Press Enter after you've updated the Azure firewall rules..."

echo ""
echo "🧪 Testing connection now..."

# Simple connection test without timeout
psql -h life-stream-postgres.postgres.database.azure.com -p 5432 -U lifestream_admin postgres -c "SELECT 'Connection successful!' as status;" 2>&1

if [ $? -eq 0 ]; then
    echo ""
    echo "🎉 SUCCESS! Azure PostgreSQL connection is now working!"
    echo ""
    echo "📋 Next steps:"
    echo "1. Run: ./analyze-local-db.sh"
    echo "2. Run: ./migrate-to-azure.sh"
else
    echo ""
    echo "❌ Connection still not working. Please check:"
    echo "1. Firewall rules were saved correctly"
    echo "2. Your IP address hasn't changed"
    echo "3. Azure PostgreSQL server is running"
    echo ""
    echo "💡 Try running this diagnostic again: ./diagnose-azure-connection.sh"
fi
