#!/bin/bash

echo "🔍 Git Commit Guide for Azure Deployment"
echo "========================================"
echo ""

echo "✅ SAFE TO COMMIT (contains no sensitive data):"
echo "  .gitignore - Updated to allow production configs"
echo "  .env.production - Frontend Azure URL only"
echo "  backend/.env.production - Non-sensitive backend config"
echo "  backend/index.js - Updated CORS configuration"
echo "  staticwebapp.config.json - Static Web App configuration"
echo "  *.md files - Documentation"
echo "  *.sh files - Helper scripts"
echo "  azure-test.html - Testing tool"
echo ""

echo "❌ DO NOT COMMIT (contains sensitive data):"
echo "  .env.azure - Contains database passwords"
echo "  backend/.env.azure - Contains database passwords"
echo "  .env - Local development (already ignored)"
echo "  backend/.env - Local development (already ignored)"
echo ""

echo "🚀 Commands to commit the safe files:"
echo ""
echo "git add .gitignore"
echo "git add .env.production"
echo "git add backend/.env.production"
echo "git add backend/index.js"
echo "git add staticwebapp.config.json"
echo "git add *.md"
echo "git add *.sh"
echo "git add azure-test.html"
echo ""
echo "git commit -m 'Configure Azure deployment with safe environment files'"
echo "git push origin main"
echo ""

echo "⚠️  REMEMBER: Set sensitive environment variables in Azure Portal:"
echo "   Database credentials, session secrets, etc."
